/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripTripIdVoteRouteImport } from './routes/trip.$tripId.vote'
import { Route as TripTripIdPreferencesRouteImport } from './routes/trip.$tripId.preferences'
import { Route as TripTripIdMoodboardRouteImport } from './routes/trip.$tripId.moodboard'
import { Route as TripTripIdItineraryRouteImport } from './routes/trip.$tripId.itinerary'
import { Route as TripTripIdConflictsRouteImport } from './routes/trip.$tripId.conflicts'

const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdVoteRoute = TripTripIdVoteRouteImport.update({
  id: '/trip/$tripId/vote',
  path: '/trip/$tripId/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdPreferencesRoute = TripTripIdPreferencesRouteImport.update({
  id: '/trip/$tripId/preferences',
  path: '/trip/$tripId/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdMoodboardRoute = TripTripIdMoodboardRouteImport.update({
  id: '/trip/$tripId/moodboard',
  path: '/trip/$tripId/moodboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdItineraryRoute = TripTripIdItineraryRouteImport.update({
  id: '/trip/$tripId/itinerary',
  path: '/trip/$tripId/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdConflictsRoute = TripTripIdConflictsRouteImport.update({
  id: '/trip/$tripId/conflicts',
  path: '/trip/$tripId/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/trip/$tripId/conflicts': typeof TripTripIdConflictsRoute
  '/trip/$tripId/itinerary': typeof TripTripIdItineraryRoute
  '/trip/$tripId/moodboard': typeof TripTripIdMoodboardRoute
  '/trip/$tripId/preferences': typeof TripTripIdPreferencesRoute
  '/trip/$tripId/vote': typeof TripTripIdVoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/trip/$tripId/conflicts': typeof TripTripIdConflictsRoute
  '/trip/$tripId/itinerary': typeof TripTripIdItineraryRoute
  '/trip/$tripId/moodboard': typeof TripTripIdMoodboardRoute
  '/trip/$tripId/preferences': typeof TripTripIdPreferencesRoute
  '/trip/$tripId/vote': typeof TripTripIdVoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/trip/$tripId/conflicts': typeof TripTripIdConflictsRoute
  '/trip/$tripId/itinerary': typeof TripTripIdItineraryRoute
  '/trip/$tripId/moodboard': typeof TripTripIdMoodboardRoute
  '/trip/$tripId/preferences': typeof TripTripIdPreferencesRoute
  '/trip/$tripId/vote': typeof TripTripIdVoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/trip/$tripId/conflicts'
    | '/trip/$tripId/itinerary'
    | '/trip/$tripId/moodboard'
    | '/trip/$tripId/preferences'
    | '/trip/$tripId/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/trip/$tripId/conflicts'
    | '/trip/$tripId/itinerary'
    | '/trip/$tripId/moodboard'
    | '/trip/$tripId/preferences'
    | '/trip/$tripId/vote'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/trip/$tripId/conflicts'
    | '/trip/$tripId/itinerary'
    | '/trip/$tripId/moodboard'
    | '/trip/$tripId/preferences'
    | '/trip/$tripId/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  TripTripIdConflictsRoute: typeof TripTripIdConflictsRoute
  TripTripIdItineraryRoute: typeof TripTripIdItineraryRoute
  TripTripIdMoodboardRoute: typeof TripTripIdMoodboardRoute
  TripTripIdPreferencesRoute: typeof TripTripIdPreferencesRoute
  TripTripIdVoteRoute: typeof TripTripIdVoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId/vote': {
      id: '/trip/$tripId/vote'
      path: '/trip/$tripId/vote'
      fullPath: '/trip/$tripId/vote'
      preLoaderRoute: typeof TripTripIdVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId/preferences': {
      id: '/trip/$tripId/preferences'
      path: '/trip/$tripId/preferences'
      fullPath: '/trip/$tripId/preferences'
      preLoaderRoute: typeof TripTripIdPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId/moodboard': {
      id: '/trip/$tripId/moodboard'
      path: '/trip/$tripId/moodboard'
      fullPath: '/trip/$tripId/moodboard'
      preLoaderRoute: typeof TripTripIdMoodboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId/itinerary': {
      id: '/trip/$tripId/itinerary'
      path: '/trip/$tripId/itinerary'
      fullPath: '/trip/$tripId/itinerary'
      preLoaderRoute: typeof TripTripIdItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId/conflicts': {
      id: '/trip/$tripId/conflicts'
      path: '/trip/$tripId/conflicts'
      fullPath: '/trip/$tripId/conflicts'
      preLoaderRoute: typeof TripTripIdConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  TripTripIdConflictsRoute: TripTripIdConflictsRoute,
  TripTripIdItineraryRoute: TripTripIdItineraryRoute,
  TripTripIdMoodboardRoute: TripTripIdMoodboardRoute,
  TripTripIdPreferencesRoute: TripTripIdPreferencesRoute,
  TripTripIdVoteRoute: TripTripIdVoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
